# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from AfSimLib import AfSim_pb2 as AfSim__pb2


class AfSimGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsSimulationPaused = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/IsSimulationPaused',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.BoolResult.FromString,
                )
        self.GetSimulationState = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/GetSimulationState',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.IntResult.FromString,
                )
        self.SetNumOfStepToAdvance = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/SetNumOfStepToAdvance',
                request_serializer=AfSim__pb2.NumOfStepToAdvance.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )
        self.GetNumOfStepToAdvance = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/GetNumOfStepToAdvance',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.NumOfStepToAdvance.FromString,
                )
        self.GetData = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/GetData',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )
        self.GetCustomData = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/GetCustomData',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )
        self.RunScript = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/RunScript',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )
        self.GetSimulationType = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/GetSimulationType',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.IntResult.FromString,
                )
        self.SendFile = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/SendFile',
                request_serializer=AfSim__pb2.FileInfo.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/DeleteFile',
                request_serializer=AfSim__pb2.FileInfo.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )
        self.OpenScenario = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/OpenScenario',
                request_serializer=AfSim__pb2.FileInfo.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )
        self.GetTracksData = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/GetTracksData',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )
        self.UpdatePlatforms = channel.unary_unary(
                '/AfSimGrpc.AfSimGrpcService/UpdatePlatforms',
                request_serializer=AfSim__pb2.DefaultPara.SerializeToString,
                response_deserializer=AfSim__pb2.ServerReply.FromString,
                )


class AfSimGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IsSimulationPaused(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNumOfStepToAdvance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumOfStepToAdvance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTracksData(self, request, context):
        """以下函数，仅用于和WarSim互联
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlatforms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AfSimGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsSimulationPaused': grpc.unary_unary_rpc_method_handler(
                    servicer.IsSimulationPaused,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.BoolResult.SerializeToString,
            ),
            'GetSimulationState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationState,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.IntResult.SerializeToString,
            ),
            'SetNumOfStepToAdvance': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNumOfStepToAdvance,
                    request_deserializer=AfSim__pb2.NumOfStepToAdvance.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
            'GetNumOfStepToAdvance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumOfStepToAdvance,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.NumOfStepToAdvance.SerializeToString,
            ),
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
            'GetCustomData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomData,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
            'RunScript': grpc.unary_unary_rpc_method_handler(
                    servicer.RunScript,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
            'GetSimulationType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationType,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.IntResult.SerializeToString,
            ),
            'SendFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFile,
                    request_deserializer=AfSim__pb2.FileInfo.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=AfSim__pb2.FileInfo.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
            'OpenScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenScenario,
                    request_deserializer=AfSim__pb2.FileInfo.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
            'GetTracksData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTracksData,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
            'UpdatePlatforms': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlatforms,
                    request_deserializer=AfSim__pb2.DefaultPara.FromString,
                    response_serializer=AfSim__pb2.ServerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AfSimGrpc.AfSimGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AfSimGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IsSimulationPaused(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/IsSimulationPaused',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.BoolResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimulationState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/GetSimulationState',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.IntResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetNumOfStepToAdvance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/SetNumOfStepToAdvance',
            AfSim__pb2.NumOfStepToAdvance.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNumOfStepToAdvance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/GetNumOfStepToAdvance',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.NumOfStepToAdvance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/GetData',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCustomData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/GetCustomData',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/RunScript',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimulationType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/GetSimulationType',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.IntResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/SendFile',
            AfSim__pb2.FileInfo.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/DeleteFile',
            AfSim__pb2.FileInfo.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/OpenScenario',
            AfSim__pb2.FileInfo.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTracksData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/GetTracksData',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePlatforms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AfSimGrpc.AfSimGrpcService/UpdatePlatforms',
            AfSim__pb2.DefaultPara.SerializeToString,
            AfSim__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
